### ISSUE TITLE
Labelers

### ISSUE THREAD

**Issue by renatocf** [topsframework/tops#9]
New front-end for Viterbi, CYK, Posterior Decoding, etc. algorithms, which create a labeling for sequences of symbols.

**Comment by renatocf** [comment]
@igorbonadio,

I took a look in the `Labeler` implementation, and I was thinking: aren't we having a cache replication? For example: in HMM, when we create a `CachedLabeler`, we need matrices `gamma` and `posterior_decoding`. When we create a `CachedEvaluator`, we need a `prefix_sum_array` vector. And as we have a single `Cache` struct, and create objects from both classes, we have this data replicated.

Do you believe we should separate this `Cache` structs in two objects? Something like an `EvaluatorCache` and `LabelerCache`? Or perhaps we could use something like an union. This would spare some memory, but I'm not sure if the extra complexity would pollute our design. Anyway, I though it would be better if we discussed that.

**Comment by igorbonadio** [comment]
Yes. There is a cache replication... But I think we can live with it as caches are very small objects.

At this moment I think we shouldn't change it. Let finish this refactoring, and, who knows, in the future we would change it.

**Comment by igorbonadio** [comment]
I found another issue: The viterbi method is defined in DecodableModelCrtp and so HMM and GHMM implement it. But they didn't share code. And it is a private method, then it will not be needed by the interface.

It seems useless...

My proposal is to make viterbi a concrete method instead of a virtual method. What do you @renatocf  think?

**Comment by renatocf** [comment]
Hum... I see no problems in letting them a subclass method. Just to remember: `labeling` just delegate, accordingly to the labeling method, to `viterbi` or `posterior_decoding`, isn't there right? Because in this case, we'd just have a minor replication when implementing this method on HMM and GHMM. Nevertheless, Covariance Models have no `viterbi`, but instead the CYK algorithm to find the best path. So it would be appropriate.

**Comment by renatocf** [comment]
Hum... I see no problems in letting them as subclass concrete methods. Just to remember: `labeling` just delegates, accordingly to the labeling method, to `viterbi` or `posterior_decoding`, doesn't it? Because in this case, we'd just have a minor replication when implementing this method on HMM and GHMM. Nevertheless, Covariance Models have no `viterbi`, but a `CYK` algorithm to find the best path. So it would be appropriate let each one delegate to its own algorithms.

**Comment by igorbonadio** [comment]
Yes. All decodable models should implement labeling. And each model should implement its own algorithm.

**Comment by renatocf** [comment]
@igorbonadio,

I was checking the code and I saw you created a `labelingLabeler` method in `DecodableModelCRTP`. I think this name is weird, and I guess you picked it to make a parallel with `labelingGenerator` and `labelingEvaluator` methods. Well, as there is no `sequenceLabeler`, I believe we could change it just to `labeler`, as it already remember us that this method is related to labels and, therefore, should be a method from decodable model. What do you think?

Also, the method is not marked `overriden` and has no purely virtual version available in `DecodableModel`. Please, take a look on that too.

**Comment by igorbonadio** [comment]
@renatocf I will check it. Thanks!
